## traefik.yml
accesslog: true

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

log:
  level: INFO

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: endpoint
    watch: true